# Site settings
title: Needmore Designs
email: ray@needmoredesigns.com
description: > # this means to ignore newlines until "baseurl:"
  Prototype of new Needmore Designs website.
baseurl: "/needmore-jekyll" # the subpath of your site, e.g. /blog/
url: "http://needmoredesigns.com" # the base hostname & protocol for your site
twitter_username: needmore
github_username:  needmoredesigns

# Build settings
markdown: kramdown
